# Generated by Django 6.0.4 on 2026-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_smsmessagelog_smsoptin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('morning', 'Morning Greeting'), ('midday', 'Lunch/Nap'), ('pickup', 'Pickup Reminder')], max_length=20, unique=True)),
                ('body_template', models.TextField(help_text='Use placeholders like {student_name}, {first_name}, {last_name}, {quote}.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
