# Generated by Django 6.0.4 on 2026-04-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('badge_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('homeroom', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('directives', models.TextField(blank=True)),
            ],
        ),
    ]
